
```{r}
rm(list=ls())
int.polation = 100
win.size = round(int.polation*.04)
win.size2 = 25
cluster.try = 3


file.name0 = "FullTest 4_hc.txt"
file.name1 = "FullTest 4_kc.txt"
file.name2 = "Number_of_sets_per_cluster"
file.name3 = paste("Dendrogram_int",paste(int.polation,paste("_win",win.size, sep = ""), sep = ""), sep = "")
file.name4 = "TEST TEMP.txt"
name.clustering = paste("Cluster_Images_",paste(int.polation,paste("_win",win.size, sep = ""), sep = ""), sep = "")
name.clustering2 = paste("Cluster_Images_int_2",paste(int.polation,paste("_win",win.size, sep = ""), sep = ""), sep = "")

```




```{r, message=FALSE}
set.seed(12347)

require(dtwclust)
require(TSclust)
require(TSdist)
require(dtw)
require(clusterSim)
require(cluster)
require(TTR)
require(RSNNS)


#_good_data_have    larger_selected    _larger_selected
data = read.csv("Data_Matrix_Combind_All.csv", header=TRUE)


for (i in 1:length((data[1,]))){
  f = data[,i][1:length(which(!is.na(data[,i])))]
  data.norm <-  data.Normalization(f,type="n4",normalization="column")
  dist.f = length(data[,i]) - length(which(!is.na(data[,i])))
  data.norm = c(data.norm, matrix(data=NA,nrow=1,ncol=dist.f))
  data[,i] = data.norm
}


result = matrix(data=NA, nrow = length(data[1,]), ncol = length(data[1,]))

tic=proc.time()[3]

for (i in 1:length(data[1,])) { 
  for (j in 1:length(data[1,])) {
    if (j >= i){
      next
    }
    G1 = data[,i][1:length(which(!is.na(data[,i])))]
    G2 = data[,j][1:length(which(!is.na(data[,j])))]
    #c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    
    #G1 = c(c,G1)
    #G1 = c(G1,c)
    #X1 = seq(1,length(G1),1)
    
    #G2 = c(c,G2)
    #G2 = c(G2,c)
    #X2 = seq(1,length(G2),1)
    
    G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
    G2 = approx(seq(1,length(G2),1), y = G2, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
    
    G1.x = G1$x
    G1.y = G1$y
    #G1.y = c(G1$y,c)
    #G1.y = c(c,G1.y)
    
    G2.x = G2$x
    G2.y = G2$y
    #G2.y = c(G2$y,c)
    #G2.y = c(c,G2.y)
    
    a = dtw(G1.y,G2.y,dist.method="Euclidean",step=symmetric1, keep=TRUE, window.type=slantedBandWindow,window.size=win.size)
    
    
    #print(a$distance)
    result[i,j]= a$distance#normalizedDistance
    #print(result[i,j])
  }
}
tic.stop=proc.time()[3] - tic
tic.stop

mat = matrix(0, ncol = length(result[1,]), nrow = length(result[,1]))
mat.temp = NULL


for (i in 1:length(result[i,])){
  total_length = length(result[,i])
  part_length = length(which(!is.na(result[,i])))
  
  row.data = result[,i][!is.na(result[,i])]
  
  mat.temp = c(mat.temp,row.data)
}


mat[lower.tri(mat)] = mat.temp
mat = as.dist(mat)
save(result, file="FullTest1.RData")


png(paste(file.name3,paste(tools::file_path_sans_ext(file.name1)),".png"), width=750, height=500)


hc.c = hclust(mat)
par(cex=.5)
plot(hc.c)#, hang=-1


dev.off()

hc.c = hclust(mat)
par(cex=.5)
plot(hc.c)#, hang=-1

```


```{r}

kc = kmeans(mat,4)

kc
#kc$cluster
kc$size
kc$withinss

k.max = 15

wss <- sapply(1:k.max, 
              function(k){kmeans(mat, k, nstart=7)$tot.withinss})


png("K-Means within sum of squares.png", width=750, height=500)

plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

dev.off()

plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

```


```{r}

plot(silhouette(cutree(hc.c,3),mat))

```


```{r, message=FALSE}

tree = cutree(hc.c, k = 4)

data.assign1 = t(rbind(colnames(data)[1], tree[1]))

for (i in 2:length(result[i,])){
  data.assign2 = t(rbind(colnames(data)[i], tree[i]))
  data.assign1 = rbind(data.assign1, data.assign2)
}

#print(data.assign1)



write.matrix(data.assign1, file = file.name0)

```


```{r, message=FALSE}

kc = kmeans(mat,4)

#kc
kc$size


table.replace1 = t(rbind(colnames(data)[1], kc$cluster[[1]]))

for (i in 1:length(kc$cluster)){
  table.replace2 = t(rbind(colnames(data)[i], kc$cluster[[i]]))
  table.replace1 = rbind(table.replace1, table.replace2)
}


write.matrix(kc$size, file=paste(file.name2,file.name1))
write.matrix(table.replace1, file = file.name1)

```


```{r}

rm(cluster.list)
table = read.table(file.name1)

png(paste(name.clustering,paste(tools::file_path_sans_ext(file.name1)),".png"), width=750, height=500)

table = table[2:length(table[,1]),]

roundUpNice <- function(x, nice=c(1,2,4,6,8,10)) {
    if(length(x) != 1) stop("'x' must be of length 1")
    10^floor(log10(x)) * nice[[which(x <= 10^floor(log10(x)) * nice)[[1]]]]
}

par(mfrow=c(2,roundUpNice(max(table[,2]))/2))

print(roundUpNice(max(table[,2])))

marker = 0


for (x in seq(1,max(table[,2]),1)){
  cluster.number = x
  clear.check = 1

  for (i in seq(1:length(table[,1]))){
    if (cluster.number == table[i,2]){
      if (clear.check != 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        #G1
        #c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        #G1 = c(c,G1)
        #G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = cbind(cluster.list,G1$y)
      }
    
      if (clear.check == 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        #c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        #G1 = c(c,G1)
        #G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = matrix(G1$y)
        clear.check = 2
      }
    } #CHANGED CODE HERE
  }

  
#plot(cluster.list[,2],type="l",col="blue")
#points(cluster.list[,3],type="l",col="red")
    
  DBA = DBA(t(cluster.list),step=symmetric1, keep=TRUE,window.type=slantedBandWindow,window.size=win.size)
  
  
  
  if (marker == 0){
    data.forward = matrix(data=NA, nrow = int.polation ,ncol= max(table[,2]))
    data.forward[,x] = DBA
    marker = 1
  }
  
  if (marker == 1){
    data.forward[,x] = DBA
  }
    
  DBA = SMA(DBA,n=5)
    
  plot(seq(1,length(DBA),1),main=paste("Cluster ",cluster.number),DBA,type="l",col="blue",xlab=paste("Number of Sets in Cluster:  ",kc$size[x]), ylab="Normalized Fluorescence Intensity",cex.lab=1.25)
    #lines(G2.x,G2.y,col="red")
}

dev.off()



```




```{r}
data.test = read.csv("Matrix_vehicle.csv", header=TRUE)


DTW.FUNCTION = function(a, b){
    G1 = a
    
    b = matrix(b)
    b = na.omit(b)
    b = data.Normalization(b, type="n4", normalization = "column")[,1]
    
    G2 = b
    #c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    
    #G1 = c(c,G1)
    #G1 = c(G1,c)
    #X1 = seq(1,length(G1),1)
    
    #G2 = c(c,G2)
    #G2 = c(G2,c)
    #X2 = seq(1,length(G2),1)
    
    G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
    #G2 = approx(seq(1,length(G2),1), y = G2, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)

    
    G1.x = G1$x
    G1.y = G1$y
    
    #G2.x = G2$x
    #G2.y = G2$y
    #G1.y = c(G1$y,c)
    #G1.y = c(c,G1.y)
    
    
    d = dtw(G2,G1.y,dist.method="Euclidean",step=symmetric1, keep=TRUE, window.type=slantedBandWindow,window.size=10)
    
    return(d$distance)
}


for (i in 1:length((data.test[1,]))){
  f = data.test[,i][1:length(which(!is.na(data.test[,i])))]
  data.test.norm <-  data.Normalization(f,type="n4",normalization="column")
  dist.test.f = length(data.test[,i]) - length(which(!is.na(data.test[,i])))
  data.test.norm = c(data.test.norm, matrix(data=NA,nrow=1,ncol=dist.test.f))
  data.test[,i] = data.test.norm
}


matrix.assign = matrix(data=NA, nrow=length(data.test[1,]), ncol=2)


for (i in seq(1,length(data.test[1,]),1)){
  matrix.assignTemp = matrix(data=NA, nrow=length(data.forward[1,]), ncol = 2)
  for (x in seq(1,length(data.forward[1,]),1)){
    a = data.test[,i][1:length(which(!is.na(data.test[,i])))]
    b = data.forward[,x]
    
    distance.temp = DTW.FUNCTION(a,b)
    
    matrix.assignTemp[x,] = c(x,distance.temp)
  }
  
  
  #LOOK AT REDUNDENCY IN [1] in lines line+1and+2  
  assign = matrix.assignTemp[which.min(matrix.assignTemp[,2]),][1]
  matrix.assign[i,] = c(colnames(data.test)[i], assign[1])
}
  


write.matrix(matrix.assign, file = file.name4)




a = data.test[,42][1:length(which(!is.na(data.test[,82])))]

plot(a, type = "l")

G1 = approx(seq(1,length(a),1), y = a, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)$y

b = matrix(SMA(data.forward[,2],n=10))
b = na.omit(b)
b = data.Normalization(b, type="n4", normalization = "column")[,1]

G2 = b


plot(G1, type="l")
lines(G2)

d = dtw(G2,G1,dist.method="Euclidean",step=symmetric1, keep=TRUE, window.type=slantedBandWindow,window.size=5)


plot(G2,type="l",col="blue")
points(G1[d$index2]~d$index1,type="l",col="red")
d$distance

```





```{r}
rm(cluster.list)
table = read.table(file.name4)


count.list = sum(table[,2] == 1)
for (i in seq(2,max(as.numeric(table[,2])))){
  count.list = rbind(count.list, sum(table[,2] == i))
}
write.matrix(count.list, file="CountList.txt")
count = read.table("CountList.txt")


png(paste(name.clustering2,paste(tools::file_path_sans_ext(file.name1)),".png"), width=750, height=500)


#CHECK THIS
table = table[2:length(table[,1]),]


roundUpNice <- function(x, nice=c(1,2,4,6,8,10)) {
    if(length(x) != 1) stop("'x' must be of length 1")
    10^floor(log10(x)) * nice[[which(x <= 10^floor(log10(x)) * nice)[[1]]]]
}


par(mfrow=c(2,roundUpNice(max(table[,2]))/2))
print(roundUpNice(max(table[,2])))



marker = 0
for (x in seq(1,max(table[,2]),1)){
  cluster.number = x
  clear.check = 1

  for (i in seq(1:length(table[,1]))){
    if (cluster.number == table[i,2]){
      if (clear.check != 1){
        G1 = data.test[,i][1:length(which(!is.na(data.test[,i])))]
        #c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        #G1 = c(c,G1)
        #G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = cbind(cluster.list,G1$y)
      }
    
      if (clear.check == 1){
        G1 = data.test[,i][1:length(which(!is.na(data.test[,i])))]
        #c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        #G1 = c(c,G1)
        #G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = matrix(G1$y)
        clear.check = 2
      }
    }#CHANGED CODE HERE
  }
  
#plot(cluster.list[,2],type="l",col="blue")
#points(cluster.list[,3],type="l",col="red")
    
  DBA = DBA(t(cluster.list),step=symmetric1, keep=TRUE,window.type=slantedBandWindow,window.size=25)
  DBA = SMA(DBA,n=3)
  
  
  plot(seq(1,length(DBA),1),main=paste("Cluster ",cluster.number),DBA,type="l",col="blue",xlab=paste("Number of Sets in Cluster:  ",count[x,]), ylab="Normalized Fluorescence Intensity",cex.lab=1.25)
    #lines(G2.x,G2.y,col="red")
}

dev.off()




plot(DBA, type="l")



```

