
```{r}
rm(list=ls())
int.polation = 100
win.size = round(int.polation*.02)
win.size2 = round(int.polation*.15)
cluster.try = 3


file.name0 = "Window Variable Test 1_hc.txt"
file.name1 = "Window Variable Test 1_kc.txt"
file.name2 = "Number_of_sets_per_cluster"
file.name3 = paste("Dendrogram_int",paste(int.polation,paste("_win",win.size, sep = ""), sep = ""), sep = "")
name.clustering = paste("Cluster_Images_int_1",paste(int.polation,paste("_win",win.size, sep = ""), sep = ""), sep = "")
name.clustering2 = paste("Cluster_Images_int_2",paste(int.polation,paste("_win",win.size, sep = ""), sep = ""), sep = "")

```




```{r, message=FALSE}
set.seed(12347)

require(dtwclust)
require(TSclust)
require(TSdist)
require(dtw)
require(clusterSim)
require(cluster)
require(TTR)
require(RSNNS)


#_good_data_have    larger_selected    _larger_selected
data = read.csv("Data_Matrix_ALL_16-30.csv", header=TRUE)


for (i in 1:length((data[1,]))){
  f = data[,i][1:length(which(!is.na(data[,i])))]
  data.norm <-  data.Normalization(f,type="n4",normalization="column")
  dist.f = length(data[,i]) - length(which(!is.na(data[,i])))
  data.norm = c(data.norm, matrix(data=NA,nrow=1,ncol=dist.f))
  data[,i] = data.norm
}


result = matrix(data=NA, nrow = length(data[1,]), ncol = length(data[1,]))


for (i in 1:length(data[1,])) { 
  for (j in 1:length(data[1,])) {
    if (j >= i){
      next
    }
    G1 = data[,i][1:length(which(!is.na(data[,i])))]
    G2 = data[,j][1:length(which(!is.na(data[,j])))]
    c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    
    #G1 = c(c,G1)
    #G1 = c(G1,c)
    #X1 = seq(1,length(G1),1)
    
    #G2 = c(c,G2)
    #G2 = c(G2,c)
    #X2 = seq(1,length(G2),1)
    
    G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 3, f = 1, ties = mean)
    G2 = approx(seq(1,length(G2),1), y = G2, method="linear", n=int.polation,rule = 3, f = 1, ties = mean)
    
    G1.x = G1$x
    G1.y = c(G1$y,c)
    G1.y = c(c,G1.y)
    
    G2.x = G2$x
    G2.y = c(G2$y,c)
    G2.y = c(c,G2.y)
    
    a = dtw(G1.y,G2.y,dist.method="Euclidean",step=symmetric1, keep=TRUE, window.type=slantedBandWindow,window.size=win.size)
    
    
    #print(a$distance)
    result[i,j]= a$distance#normalizedDistance
    #print(result[i,j])
  }
}


mat = matrix(0, ncol = length(result[1,]), nrow = length(result[,1]))
mat.temp = NULL


for (i in 1:length(result[i,])){
  total_length = length(result[,i])
  part_length = length(which(!is.na(result[,i])))
  
  row.data = result[,i][!is.na(result[,i])]
  
  mat.temp = c(mat.temp,row.data)
}


mat[lower.tri(mat)] = mat.temp
mat = as.dist(mat)
save(result, file="non-smoothing 16-30.RData")


png(paste(file.name3,paste(tools::file_path_sans_ext(file.name1)),".png"), width=750, height=500)


hc.c = hclust(mat)
par(cex=.5)
plot(hc.c)#, hang=-1


dev.off()

hc.c = hclust(mat)
par(cex=.5)
plot(hc.c)#, hang=-1

```


```{r}

kc = kmeans(mat,cluster.try)

kc
#kc$cluster
kc$size
kc$withinss

k.max = 15

wss <- sapply(1:k.max, 
              function(k){kmeans(mat, k, nstart=10)$tot.withinss})


png("K-Means within sum of squares.png", width=750, height=500)

plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

dev.off()

plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

```


```{r}

plot(silhouette(cutree(hc.c,5),mat))

```


```{r, message=FALSE}

tree = cutree(hc.c, k = 4)

data.assign1 = t(rbind(colnames(data)[1], tree[1]))

for (i in 2:length(result[i,])){
  data.assign2 = t(rbind(colnames(data)[i], tree[i]))
  data.assign1 = rbind(data.assign1, data.assign2)
}

#print(data.assign1)



write.matrix(data.assign1, file = file.name0)

```


```{r, message=FALSE}

kc = kmeans(mat,4)

#kc
kc$size


table.replace1 = t(rbind(colnames(data)[1], kc$cluster[[1]]))

for (i in 1:length(kc$cluster)){
  table.replace2 = t(rbind(colnames(data)[i], kc$cluster[[i]]))
  table.replace1 = rbind(table.replace1, table.replace2)
}


write.matrix(kc$size, file=paste(file.name2,file.name1))
write.matrix(table.replace1, file = file.name1)#

```


```{r}

rm(cluster.list)
table = read.table(file.name1)

png(paste(name.clustering,paste(tools::file_path_sans_ext(file.name1)),".png"), width=750, height=500)

table = table[2:length(table[,1]),]

roundUpNice <- function(x, nice=c(1,2,4,6,8,10)) {
    if(length(x) != 1) stop("'x' must be of length 1")
    10^floor(log10(x)) * nice[[which(x <= 10^floor(log10(x)) * nice)[[1]]]]
}

par(mfrow=c(2,roundUpNice(max(table[,2]))/2))

print(roundUpNice(max(table[,2])))

marker = 0

for (x in seq(1,max(table[,2]),1)){
  cluster.number = x
  clear.check = 1

  for (i in seq(1:length(table[,1]))){
    if (cluster.number == table[i,2]){
      if (clear.check != 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        G1
        c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        G1 = c(c,G1)
        G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = cbind(cluster.list,G1$y)
      }
    }
      if (clear.check == 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        G1 = c(c,G1)
        G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = matrix(G1$y)
        clear.check = 2
      }
    }

  
#plot(cluster.list[,2],type="l",col="blue")
#points(cluster.list[,3],type="l",col="red")
  
DBA = DBA(t(cluster.list),step=symmetric1, keep=TRUE,window.type=slantedBandWindow,window.size=win.size)

if (marker == 0){
  data.forward = matrix(, nrow = int.polation ,ncol= max(table[,2]))
  data.forward[,x] = DBA
  marker = 1
}

if (marker == 1){
  data.forward[,x] = DBA
}
  
DBA = SMA(DBA,n=5)
  
plot(seq(1,length(DBA),1),main=paste("Cluster ",cluster.number),DBA,type="l",col="blue",xlab=paste("Number of Sets in Cluster:  ",kc$size[x]), ylab="Normalized Fluorescence Intensity",cex.lab=1.25)
  #lines(G2.x,G2.y,col="red")
}

dev.off()



```


```{r}
DTW.FUNCTION = function(a, b){
    G1 = a
    G2 = b
    c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    
    #G1 = c(c,G1)
    #G1 = c(G1,c)
    #X1 = seq(1,length(G1),1)
    
    #G2 = c(c,G2)
    #G2 = c(G2,c)
    #X2 = seq(1,length(G2),1)
    
    G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 3, f = 1, ties = mean)

    
    G1.x = G1$x
    G1.y = c(G1$y,c)
    G1.y = c(c,G1.y)
    
    
    a = dtw(G1.y,G2,dist.method="Euclidean",step=symmetric1, keep=TRUE, window.type=slantedBandWindow,window.size=win.size)
    
    return(a$distance)
}


data = read.csv("Data_Matrix_ALL_16-30.csv", header=TRUE)

for (i in 1:length((data[1,]))){
  f = data[,i][1:length(which(!is.na(data[,i])))]
  data.norm <-  data.Normalization(f,type="n4",normalization="column")
  dist.f = length(data[,i]) - length(which(!is.na(data[,i])))
  data.norm = c(data.norm, matrix(data=NA,nrow=1,ncol=dist.f))
  data[,i] = data.norm
}


matrix.assign = matrix(, nrow=length(data[1,]), ncol=2)
i = 41
for (i in seq(1,length(data[1,]),1)){
  matrix.assignTemp = matrix(, nrow=length(data.forward[1,]), ncol = 2)
  for (x in seq(1,length(data.forward[1,]),1)){
    a = data[,i][1:length(which(!is.na(data[,i])))]
    b = data.forward[,x]
    
    distance.temp = DTW.FUNCTION(a,b)
    
    matrix.assignTemp[x,] = c(x,distance.temp)
  }
    
  assign = matrix.assignTemp[which.min(matrix.assignTemp[,2]),][1]
  matrix.assign[i,] = c(colnames(data)[i], assign[1])
}

file.name4 = "TEST TEMP.txt"

write.matrix(matrix.assign, file = file.name4)


```



```{r}
rm(cluster.list)
table = read.table(file.name4)

png(paste(name.clustering2,paste(tools::file_path_sans_ext(file.name1)),".png"), width=750, height=500)

table = table[2:length(table[,1]),]

roundUpNice <- function(x, nice=c(1,2,4,6,8,10)) {
    if(length(x) != 1) stop("'x' must be of length 1")
    10^floor(log10(x)) * nice[[which(x <= 10^floor(log10(x)) * nice)[[1]]]]
}

par(mfrow=c(2,roundUpNice(max(table[,2]))/2))

print(roundUpNice(max(table[,2])))

marker = 0

for (x in seq(1,max(table[,2]),1)){
  cluster.number = x
  clear.check = 1

  for (i in seq(1:length(table[,1]))){
    if (cluster.number == table[i,2]){
      if (clear.check != 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        G1
        c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        G1 = c(c,G1)
        G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = cbind(cluster.list,G1$y)
      }
    }
      if (clear.check == 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        G1 = c(c,G1)
        G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = matrix(G1$y)
        clear.check = 2
      }
    }

  
#plot(cluster.list[,2],type="l",col="blue")
#points(cluster.list[,3],type="l",col="red")
  
DBA = DBA(t(cluster.list),step=symmetric1, keep=TRUE,window.type=slantedBandWindow,window.size=win.size)

if (marker == 0){
  data.forward = matrix(, nrow = int.polation ,ncol= max(table[,2]))
  data.forward[,x] = DBA
  marker = 1
}

if (marker == 1){
  data.forward[,x] = DBA
}
  
DBA = SMA(DBA,n=3)
  
plot(seq(1,length(DBA),1),main=paste("Cluster ",cluster.number),DBA,type="l",col="blue",xlab=paste("Number of Sets in Cluster:  ",kc$size[x]), ylab="Normalized Fluorescence Intensity",cex.lab=1.25)
  #lines(G2.x,G2.y,col="red")
}

dev.off()
```












































```{r}
## ART
set.seed(12347)

require(dtwclust)
require(TSclust)
require(TSdist)
require(dtw)
require(clusterSim)
require(cluster)
require(TTR)
require(RSNNS)

data = read.csv("Data_Matrix_ALL.csv", header=TRUE)


for (i in 1:length((data[1,]))){
  f = data[,i][1:length(which(!is.na(data[,i])))]
  data.norm <-  data.Normalization(f,type="n4",normalization="column")
  dist.f = length(data[,i]) - length(which(!is.na(data[,i])))
  data.norm = c(data.norm, matrix(data=NA,nrow=1,ncol=dist.f))
  data[,i] = data.norm
}
sample.size = length((data[1,]))
data.new = matrix(0, ncol = sample.size, nrow = int.polation)


for (i in 1:sample.size){
  f = data[,i][1:length(which(!is.na(data[,i])))]
  #data.norm <-  data.Normalization(f,type="n4",normalization="column")
  #dist.f = length(data[,i]) - length(which(!is.na(data[,i])))
  #data.norm = c(data.norm, matrix(data=NA,nrow=1,ncol=dist.f))
  
  data.intPol = approx(seq(1,length(f),1), y = f, method="linear", n=int.polation,rule = 3, f = 1, ties = mean)$y
  
  data.new[,i] = data.intPol
}

data.new = t(data.new)

model = art2(data.new, f2Units=5)

predictions <- predict(model, data.new)
predictions

rm(table.NN1, table.NN2)

for (i in 1){
  for (j in 1:length(predictions[1,])){
    if (predictions[i,j] > 0){
      table.NN1 = t(rbind(colnames(data)[1], j))
      next
    
  }
  }
}

for (i in 1:length(predictions[,1])){
  set = 0
  for (j in 1:length(predictions[i,])){
    if (j==length(predictions[i,])){
      if (predictions[i,j] == 0){
        if (set == 0){
          table.NN2 = t(rbind(colnames(data)[i], j))
          table.NN1 = rbind(table.NN1, table.NN2)
        }
      }
    }
    if (predictions[i,j] > 0){
      table.NN2 = t(rbind(colnames(data)[i], j))
      table.NN1 = rbind(table.NN1, table.NN2)
      set = 1
    next
    }

  }
}

count.0 = sum(table.NN1[,2] == 0)
count.1 = sum(table.NN1[,2] == 1)
count.2 = sum(table.NN1[,2] == 2)
count.3 = sum(table.NN1[,2] == 3)
count.4 = sum(table.NN1[,2] == 4)
count.5 = sum(table.NN1[,2] == 5)
count.6 = sum(table.NN1[,2] == 6)
count.7 = sum(table.NN1[,2] == 7)
count.8 = sum(table.NN1[,2] == 8)
count.9 = sum(table.NN1[,2] == 9)
count.10 = sum(table.NN1[,2] == 10)

print(count.0+count.1+count.2+count.3+count.4+count.5+count.6+count.7+count.8+count.9+count.10)

count.list = count.1
count.list = rbind(count.list, count.2)
count.list = rbind(count.list, count.3)
count.list = rbind(count.list, count.4)
count.list = rbind(count.list, count.5)
count.list = rbind(count.list, count.6)
count.list = rbind(count.list, count.7)
count.list = rbind(count.list, count.8)
count.list = rbind(count.list, count.9)
count.list = rbind(count.list, count.10)

NN.name1 = "NN_ALL_ASSIGN_TEST.txt"
NN.name2 = "NN_ALL_ASSIGN_TEST_COUNT.txt"

write.matrix(count.list, file=NN.name1)
write.matrix(table.NN1, file =NN.name2)

```


```{r}

rm(cluster.list)
table = read.table(NN.name2, row.names=NULL)
count = read.table(NN.name1)
name.clustering = "IMAGES_FOR_NN_TEST_"

png(paste(name.clustering,paste(tools::file_path_sans_ext(NN.name1)),".png"), width=750, height=500)

table = table[2:length(table[,1]),]

roundUpNice <- function(x, nice=c(1,2,4,6,8,10)) {
    if(length(x) != 1) stop("'x' must be of length 1")
    10^floor(log10(x)) * nice[[which(x <= 10^floor(log10(x)) * nice)[[1]]]]
}

par(mfrow=c(2,roundUpNice(max(table[,2]))/2))

print(roundUpNice(max(table[,2])))


data = read.csv("Data_Matrix_ALL.csv", header=TRUE)


for (i in 1:length((data[1,]))){
  f = data[,i][1:length(which(!is.na(data[,i])))]
  data.norm <-  data.Normalization(f,type="n4",normalization="column")
  dist.f = length(data[,i]) - length(which(!is.na(data[,i])))
  data.norm = c(data.norm, matrix(data=NA,nrow=1,ncol=dist.f))
  data[,i] = data.norm
}


for (x in seq(1,max(table[,2]),1)){
  cluster.number = x
  clear.check = 1

  for (i in seq(1:length(table[,1]))){
    if (cluster.number == table[i,2]){
      if (clear.check != 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        G1
        c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        G1 = c(c,G1)
        G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = cbind(cluster.list,G1$y)
      }
    }
      if (clear.check == 1){
        G1 = data[,i][1:length(which(!is.na(data[,i])))]
        c = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
        
        G1 = c(c,G1)
        G1 = c(G1,c)
        X1 = seq(1,length(G1),1)
        G1 = approx(seq(1,length(G1),1), y = G1, method="linear", n=int.polation,rule = 2, f = 1, ties = mean)
        cluster.list = matrix(G1$y)
        clear.check = 2
      }
    }

  
#plot(cluster.list[,2],type="l",col="blue")
#points(cluster.list[,3],type="l",col="red")
  
DBA = DBA(t(cluster.list),step=symmetric1, keep=TRUE,window.type=slantedBandWindow,window.size=win.size)
  
DBA = SMA(DBA,n=3)
  
plot(seq(1,length(DBA),1),main=paste("Cluster ",cluster.number),DBA,type="l",col="blue",xlab=paste("Number of Sets in Cluster:  ",count[x,]), ylab="Normalized Fluorescence Intensity",cex.lab=1.25)
  #lines(G2.x,G2.y,col="red")
}

dev.off()


```



```{r}



data(snnsData)
patterns <- snnsData$art2_tetra_med.pat

#par(mfrow=c(3,length(patterns[,1])))

patterns

model <- art2(patterns, f2Units=5, learnFuncParams=c(0.99, 20, 20, 0.1, .3),
updateFuncParams=c(0.99, 20, 20, 0.1, .3))
model
testPatterns <- snnsData$art2_tetra_high.pat
predictions <- predict(model, testPatterns)

#plot(patterns[,1], type="line")

predictions
for (i in seq(1,length(patterns[,1])-10,1)){
plot(patterns[i,], type="line")
}


```

